[package]
name = "av"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
homepage = "https://github.com/rust-av/rust-av"
keywords = ["multimedia"]
license = "MIT"

[features]
nightly = []

[dependencies.av-data]
path = "data"
version = "*"

[dependencies.av-format]
path = "format"
version = "*"

[dependencies.av-bitstream]
path = "bitstream"
version = "*"

[dependencies.av-codec]
path = "codec"
version = "*"

[workspace]
members = [
    "bitstream",
    "codec",
    "data",
    "format",
]
